version: '3.8'
services:
   jenkins:
     container_name: jenkins-blueocean
     build: .
     ports:
       - "8080:8080"
     volumes:
       - jenkins_data:/var/jenkins_home
       - /var/run/docker.sock:/var/run/docker.sock
     networks:
        - jenkins

networks:
  jenkins:
       name: jenkins
volumes:
  jenkins_data:
